src/Loja.Admin/Models/ErrorViewModel.cs
namespace Loja.Admin.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Loja.Admin/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace Loja.Admin.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Loja.Admin/Controllers/AgendamentoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Loja.Admin.Controllers
{    
    public class AgendamentoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult Edicao()
        {
            return View();
        }

        public IActionResult Calendario()
        {
            return View();
        }

        public IActionResult Visualizar()
        {
            return View();
        }
    }
}

src/Loja.Admin/Controllers/AtendimentoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Loja.Admin.Controllers
{    
    public class AtendimentoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult Edicao()
        {
            return View();
        }

        public IActionResult Visualizar()
        {
            return View();
        }
    }
}

src/Loja.Admin/Controllers/EstabelecimentoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Loja.Admin.Controllers 
{    
    public class EstabelecimentoController : Controller
    {       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult Edicao()
        {
            return View();
        }

        public IActionResult Visualizar()
        {
            return View();
        }
    }
}

src/Loja.Admin/Controllers/HomeController.cs
using Loja.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Loja.Admin.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Loja.Admin/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace Loja.Admin.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Loja.Admin/Controllers/PerfilController.cs
using Microsoft.AspNetCore.Mvc;

namespace Loja.Admin.Controllers{
    
    public class PerfilController : Controller
    {       
        public IActionResult Index(string id)
        {
            return View();
        }
    }
}

src/Loja.Admin/Controllers/RecuperarSenhaController.cs
using Microsoft.AspNetCore.Mvc;

namespace Loja.Admin.Controllers
{
    [Route("recuperar-senha")]
    public class RecuperarSenhaController : Controller
    {
        [Route("atualizar-senha")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Loja.Admin/Controllers/ServicoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Loja.Admin.Controllers
{    
    public class ServicoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult Edicao()
        {
            return View();
        }

        public IActionResult Visualizar()
        {
            return View();
        }
    }
}

src/Loja.Admin/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace Loja.Admin.Controllers
{    
    public class UsuarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Cadastro()
        {
            return View();
        }

        public IActionResult Edicao()
        {
            return View();
        }

        public IActionResult Visualizar()
        {
            return View();
        }
    }
}

src/Loja.Admin/Views/Agendamento/Cadastro.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {
    
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Cadastro de Agendamento</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a asp-controller="Agendamento" asp-action="Index">Agendamentos</a></li>
                    <li class="breadcrumb-item active">Cadastrar</li>
                </ol>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form data-bind="with:agendamento">
                    <div class="form-row">
                        <!-- ko if:  $root.estabelecimentos().length > 0 -->
                        <div class="form-group col-md-6">
                            <label for="estabelecimento" class="col-form-label">Estabelecimento<span class="text-danger">*</span></label>
                            <select id="estabelecimento" class="form-control" data-toggle="select2"
                                    data-bind="value: estabelecimentoId, options: $root.estabelecimentos, optionsText: 'nome', optionsValue: 'estabelecimentoId', valueAllowUnset: true, select2: { placeholder: 'Selecione um estabelecimento', tags: false }">
                            </select>
                        </div>
                        <!-- /ko-->
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="cliente" class="col-form-label">Cliente<span class="text-danger">*</span></label>
                            <select id="cliente" class="form-control" data-toggle="select2"
                                    data-bind="value: userId, options: $root.clientes, optionsText: 'nome', optionsValue: 'userId', valueAllowUnset: true, select2: { placeholder: 'Selecione um cliente', tags: false }">
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="servico" class="col-form-label">Serviço<span class="text-danger">*</span></label>
                            <select id="servico" class="form-control" data-toggle="select2"
                                    data-bind="value: servicoId, options: $root.servicos, optionsText: 'nome', optionsValue: 'servicoId', valueAllowUnset: true, select2: { placeholder: 'Selecione um serviço', tags: false }">
                            </select>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="dataAgendamento" class="col-form-label">Data Agendamento<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="dataAgendamento" placeholder="Informe a data agendamento"
                                   data-bind="datepicker: dataAgendamentoDP, datepickerOptions: { startDate: new Date() }, mask: '99/99/9999', value: dataAgendamentoStr" autocomplete="off" />
                        </div>
                        <div class="form-group col-md-4">
                            <label for="horaInicial" class="col-form-label">Horário Inicial<span class="text-danger">*</span></label>
                            <select id="horaInicial" class="form-control" data-toggle="select2"
                                    data-bind="value: horaInicial, options: $root.horariosDisponiveis, optionsText: 'horarioInicial', optionsValue: 'horarioInicial', valueAllowUnset: true, select2: { placeholder: 'Selecione um horário', tags: false }">
                            </select>                            
                        </div>
                        <div class="form-group col-md-4">
                            <label for="horaFinal" class="col-form-label">Horário Final</label>
                            <input type="text" class="form-control" id="horaFinal" data-bind="value: horaFinal, disable:true" readonly>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="observacao" class="col-form-label">Observação</label>
                            <textarea class="form-control" id="observacao" rows="5" data-bind="value: observacao" placeholder="Informe a observação"></textarea>
                        </div>
                    </div>
                    <div class="form-group float-right">
                        <button type="button" class="btn btn-secondary mr-1" data-bind="click: $parent.voltar">Voltar</button>
                        <button type="button" class="btn btn-primary" data-bind="click: $parent.salvar, disable: $parent.bloqueiaSalvar()">Salvar</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@section scripts {   
    <script src="~/js/agendamentoCadastro.min.js"></script>
}

src/Loja.Admin/Views/Agendamento/Edicao.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {
    
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Edição de Agendamento</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a asp-controller="Agendamento" asp-action="Index">Agendamentos</a></li>
                    <li class="breadcrumb-item active">Editar</li>
                </ol>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form data-bind="with:agendamento">
                    <div class="form-row">
                        <!-- ko if:  $root.estabelecimentos().length > 0 -->
                        <div class="form-group col-md-6">
                            <label for="estabelecimento" class="col-form-label">Estabelecimento<span class="text-danger">*</span></label>
                            <select id="estabelecimento" class="form-control" data-toggle="select2"
                                    data-bind="value: estabelecimentoId, options: $root.estabelecimentos, optionsText: 'nome', optionsValue: 'estabelecimentoId', valueAllowUnset: true, select2: { placeholder: 'Selecione um estabelecimento', tags: false }">
                            </select>
                        </div>
                        <!-- /ko-->
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="cliente" class="col-form-label">Cliente<span class="text-danger">*</span></label>
                            <select id="cliente" class="form-control" data-toggle="select2"
                                    data-bind="value: userId, options: $root.clientes, optionsText: 'nome', optionsValue: 'userId', valueAllowUnset: true, select2: { placeholder: 'Selecione um cliente', tags: false }">
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="servico" class="col-form-label">Serviço<span class="text-danger">*</span></label>
                            <select id="servico" class="form-control" data-toggle="select2"
                                    data-bind="value: servicoId, options: $root.servicos, optionsText: 'nome', optionsValue: 'servicoId', valueAllowUnset: true, select2: { placeholder: 'Selecione um serviço', tags: false }">
                            </select>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="dataAgendamento" class="col-form-label">Data Agendamento<span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="dataAgendamento" placeholder="Informe a data agendamento"
                                   data-bind="datepicker: dataAgendamentoDP, datepickerOptions: { startDate: new Date() }, mask: '99/99/9999', value: dataAgendamentoStr" autocomplete="off" />
                        </div>
                        <div class="form-group col-md-4">
                            <label for="horaInicial" class="col-form-label">Horário Inicial<span class="text-danger">*</span></label>
                            <select id="horaInicial" class="form-control" data-toggle="select2"
                                    data-bind="value: horaInicial, options: $root.horariosDisponiveis, optionsText: 'horarioInicial', optionsValue: 'horarioInicial', valueAllowUnset: true, select2: { placeholder: 'Selecione um horário', tags: false }">
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label for="horaFinal" class="col-form-label">Horário Final</label>
                            <input type="text" class="form-control" id="horaFinal" data-bind="value: horaFinal, disable:true" readonly>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="observacao" class="col-form-label">Observação</label>
                            <textarea class="form-control" id="observacao" rows="5" data-bind="value: observacao" placeholder="Informe a observação"></textarea>
                        </div>
                    </div>

                    <div class="form-group float-right">
                        <button type="button" class="btn btn-secondary mr-1" data-bind="click: $parent.voltar">Voltar</button>
                        <button type="button" class="btn btn-primary" data-bind="click: $parent.salvar, disable: $parent.bloqueiaSalvar()">Salvar</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@section scripts {   
    <script src="~/js/agendamentoEdicao.min.js"></script>
}

src/Loja.Admin/Views/Agendamento/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {
    <link href="~/css/datatable.min.css" rel="stylesheet" type="text/css" />
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Agendamentos</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item active">Agendamentos</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="float-right">
            <a asp-controller="Agendamento" asp-action="Cadastro" class="btn btn-primary waves-effect waves-light mb-3">
                <i class="fa fa-plus-circle mr-1"></i> Novo
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <table id="datatable-agendamento" class="table table-striped dt-responsive nowrap w-100">
                            <thead>
                                <tr>
                                    <th>Código</th>
                                    <th>Data Agendamento</th>
                                    <th>Data Final Agendamento</th>
                                    <th>Cliente</th>
                                    <th>Serviço</th>
                                    <th>Situação</th>
                                    <th>Estabelecimento</th>
                                    <th>Opções</th>
                                </tr>
                            </thead>
                            <tbody data-bind="foreach: agendamentos">
                                <tr>
                                    <td data-bind="text: agendamentoId"></td>
                                    <td data-bind="text: dataAgendamentoStr() + ' ' + horaInicial()"></td>
                                    <td data-bind="text: dataFinalAgendamentoStr"></td>
                                    <td data-bind="text: usuarioNome"></td>
                                    <td data-bind="text: servicoNome"></td>
                                    <td data-bind="text: situacao"></td>
                                    <td data-bind="text: estabelecimentoNome"></td>
                                    <td>
                                        <button id="btnIniciarAtendimento" type="button" class="btn btn-success waves-effect waves-light" title="Iniciar Atendimento" data-bind="value: agendamentoId, visible: situacao() == 'Ativo'"><i class="mdi mdi-tag-multiple-outline"></i></button>
                                        <button id="btnVisualizar" type="button" class="btn btn-info waves-effect waves-light" title="Visualizar" data-bind="value: agendamentoId"><i class="mdi mdi-eye-outline"></i></button>
                                        <button id="btnEditar" type="button" class="btn btn-warning waves-effect waves-light" title="Editar" data-bind="value: agendamentoId, visible: situacao() == 'Ativo'"><i class="mdi mdi-pencil-outline"></i></button>
                                        <button id="btnExcluir" type="button" class="btn btn-danger waves-effect waves-light" title="Excluir" data-bind="value: agendamentoId, visible: situacao() == 'Ativo'"><i class="mdi mdi-trash-can-outline"></i></button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>                
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/js/datatable.min.js"></script>
    <script src="~/js/agendamento.min.js"></script>
}

src/Loja.Admin/Views/Atendimento/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {
    <link href="~/css/datatable.min.css" rel="stylesheet" type="text/css" />
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Atendimentos</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item active">Atendimentos</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="float-right">
            <a asp-controller="Atendimento" asp-action="Cadastro" class="btn btn-primary waves-effect waves-light mb-3">
                <i class="fa fa-plus-circle mr-1"></i> Novo
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <table id="datatable-atendimento" class="table table-striped dt-responsive nowrap w-100">
                            <thead>
                                <tr>
                                    <th>Código</th>
                                    <th>Data Atendimento</th>
                                    <th>Cliente</th>
                                    <th>Valor Total</th>
                                    <th>Situação</th>
                                    <th>Estabelecimento</th>
                                    <th>Opções</th>
                                </tr>
                            </thead>
                            <tbody data-bind="foreach: atendimentos">
                                <tr>
                                    <td data-bind="text: atendimentoId"></td>
                                    <td data-bind="text: dataAtendimento"></td>
                                    <td data-bind="text: usuarioNome"></td>
                                    <td data-bind="text: valorTotal"></td>                                    
                                    <td data-bind="text: situacao"></td>
                                    <td data-bind="text: estabelecimentoNome"></td>
                                    <td>
                                        <button id="btnFinalizarAtendimento" type="button" class="btn btn-success waves-effect waves-light" title="Finalizar Atendimento" data-bind="value: atendimentoId, visible: situacao() == 'Pendente'"><i class="mdi mdi-check-bold"></i></button>
                                        <button id="btnVisualizar" type="button" class="btn btn-info waves-effect waves-light" title="Visualizar" data-bind="value: atendimentoId"><i class="mdi mdi-eye-outline"></i></button>
                                        <button id="btnEditar" type="button" class="btn btn-warning waves-effect waves-light" title="Editar" data-bind="value: atendimentoId, visible: situacao() == 'Pendente'"><i class="mdi mdi-pencil-outline"></i></button>
                                        <button id="btnExcluir" type="button" class="btn btn-danger waves-effect waves-light" title="Cancelar" data-bind="value: atendimentoId, visible: situacao() == 'Pendente'"><i class="mdi mdi-trash-can-outline"></i></button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>                
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/js/datatable.min.js"></script>
    <script src="~/js/atendimento.min.js"></script>
}

src/Loja.Admin/Views/Estabelecimento/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section contents {
    <link href="~/css/datatable.min.css" rel="stylesheet" type="text/css" />
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Estabelecimentos</h4>
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item active">Estabelecimentos</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- ko if:  permiteCadastrar() -->
<div class="row">
    <div class="col-12">
        <div class="float-right">
            <a asp-controller="Estabelecimento" asp-action="Cadastro" class="btn btn-primary waves-effect waves-light mb-3">
                <i class="fa fa-plus-circle mr-1"></i> Novo
            </a>
        </div>
    </div>
</div>
<!-- /ko-->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <table id="datatable-estabelecimento" class="table table-striped dt-responsive nowrap w-100">
                            <thead>
                                <tr>
                                    <th>Código</th>
                                    <th>Nome</th>
                                    <th>E-mail</th>
                                    <th>Celular</th>
                                    <th>Data Cadastro</th>
                                    <th>Situação</th>
                                    <th>Opções</th>
                                </tr>
                            </thead>
                            <tbody data-bind="foreach: estabelecimentos">
                                <tr>
                                    <td data-bind="text: estabelecimentoId"></td>
                                    <td data-bind="text: nome"></td>
                                    <td data-bind="text: email"></td>
                                    <td data-bind="text: celular"></td>
                                    <td data-bind="text: dataCadastro"></td>
                                    <td data-bind="text: situacao"></td>
                                    <td>
                                        <button id="btnVisualizar" type="button" class="btn btn-info waves-effect waves-light" title="Dados Estabelecimento" data-bind="value: estabelecimentoId"><i class="mdi mdi-eye-outline"></i></button>
                                        <button id="btnEditar" type="button" class="btn btn-warning waves-effect waves-light" title="Editar" data-bind="value: estabelecimentoId, visible: situacao() == 'Ativo'"><i class="mdi mdi-pencil-outline"></i></button>
                                        <button id="btnExcluir" type="button" class="btn btn-danger waves-effect waves-light" title="Excluir" data-bind="value: estabelecimentoId, visible: $parent.permiteExcluir() && situacao() == 'Ativo'"><i class="mdi mdi-trash-can-outline"></i></button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/js/datatable.min.js"></script>
    <script src="~/js/estabelecimento.min.js"></script>
}

src/Loja.Admin/Views/Shared/_Footer.cshtml
@{ Layout = null; }

<footer class="border-top footer text-muted">
    <div>
        &copy; Leandro 2020
    </div>
</footer>

src/Loja.Admin/Views/Shared/_LeftSidebarMenu.cshtml
@{ Layout = null; }

<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">

    <!-- LOGO -->
    <div class="logo-box">
        <a href="#" onclick="redirectToPageByRole()" class="logo text-center">
            <!-- ko if:  !usuarioLogado().isAdministrador() -->
            <span class="logo-sm">
                <span class="logo-lg-text-light" data-bind="text: usuarioLogado().estabelecimentoNome()?.substr(0, 1)"></span>
            </span>
            <span class="logo-lg">
                <span class="logo-lg-text-light" data-bind="text: usuarioLogado().estabelecimentoNome()"></span>
            </span>
            <!-- /ko-->
            <!-- ko if:  usuarioLogado().isAdministrador() -->
            <span class="logo-sm">
                <span class="logo-lg-text-light">A</span>
            </span>
            <span class="logo-lg">
                <span class="logo-lg-text-light">Administrador</span>
            </span>
            <!-- /ko-->
        </a>      
    </div>

    <div class="h-100" data-simplebar>

        <!--- Sidemenu -->
        <div id="sidebar-menu">

            <ul id="side-menu">
                <!-- ko if:  exibeMenuDashboard -->
                <li>
                    <a asp-controller="Home" asp-action="Index">
                        <i class="ri-bar-chart-box-line"></i>
                        <span> Dashboard </span>
                    </a>
                </li>
                <!-- /ko-->
                <!-- ko if:  exibeMenuEstabelecimento -->
                <li>
                    <a asp-controller="Estabelecimento" asp-action="Index">
                        <i class="ri-hotel-line"></i>
                        <span> Estabelecimentos </span>
                    </a>
                </li>
                <!-- /ko-->
                <!-- ko if:  exibeMenuCalendario -->
                <li>
                    <a asp-controller="Agendamento" asp-action="Calendario">
                        <i class="ri-calendar-2-line"></i>
                        <span> Calendário </span>
                    </a>
                </li>
                <!-- /ko-->
                <!-- ko if:  exibeMenuPerfil -->
                <li>
                    <a href="javascript:void(0);" data-bind="click:redirecionarPerfil " class="dropdown-item notify-item">
                        <i class="ri-account-circle-line"></i>
                        <span> Meus Dados </span>
                    </a>
                </li>
                <!-- /ko-->
                <!-- ko if:  exibeMenuEstabelecimentoVisualizar -->
                <li>
                    <a asp-controller="Estabelecimento" asp-action="Visualizar">
                        <i class="ri-hotel-line"></i>
                        <span> Estabelecimento </span>
                    </a>
                </li>
                <!-- /ko-->
                <!-- ko if:  exibeMenuAgendamento -->
                <li>
                    <a asp-controller="Agendamento" asp-action="Index">
                        <i class="ri-time-line"></i>
                        <span> Agendamentos </span>
                    </a>
                </li>
                <!-- /ko-->
                <!-- ko if:  exibeMenuAtendimento -->
                <li>
                    <a asp-controller="Atendimento" asp-action="Index">
                        <i class="ri-file-list-line"></i>
                        <span> Atendimentos </span>
                    </a>
                </li>
                <!-- /ko-->
                <!-- ko if:  exibeMenuServico -->
                <li>
                    <a asp-controller="Servico" asp-action="Index">
                        <i class="ri-inbox-line"></i>
                        <span> Serviços </span>
                    </a>
                </li>
                <!-- /ko-->
                <!-- ko if:  exibeMenuUsuario -->
                <li>
                    <a asp-controller="Usuario" asp-action="Index">
                        <i class="ri-account-box-line"></i>
                        <span> Usuários </span>
                    </a>
                </li>
                <!-- /ko-->
                <li>
                    <a href="javascript:void(0);" class="dropdown-item notify-item" data-bind="click:function() { logoff(); }">
                        <i class="ri-logout-box-line"></i>
                        <span>Sair</span>
                    </a>
                </li>

            </ul>

        </div>
        <!-- End Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>
<!-- Left Sidebar End -->